name: base
channels:
  - conda-forge
dependencies:
  - python==3.11.11
  - conda
  - mamba[version='>=1.5.12']
  - pip
  - matplotlib
  - pandas
  - scikit-learn
  - seaborn
  - ipykernel
  - pytorch-gpu
